# Generated by Django 2.1.7 on 2019-03-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backpack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('p_type', models.CharField(max_length=10)),
                ('p_name', models.CharField(max_length=20)),
                ('p_count', models.IntegerField(default=0)),
            ],
        ),
    ]
